"""Add new vault table for encrypted storage of documents and remove other old tables

Revision ID: 8957b829e895
Revises: c_add_nonces_table
Create Date: 2026-02-14 16:31:24.724095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8957b829e895'
down_revision: Union[str, Sequence[str], None] = 'c_add_nonces_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet', sa.String(length=255), nullable=False),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('encrypted_toc', sa.Text(), nullable=False),
    sa.Column('toc_signature', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_wallet', 'doc_hash', name='uq_vaults_owner_doc')
    )
    op.create_index('idx_vaults_created_at', 'vaults', ['created_at'], unique=False)
    op.create_index('idx_vaults_doc_hash', 'vaults', ['doc_hash'], unique=False)
    op.create_index('idx_vaults_owner_wallet', 'vaults', ['owner_wallet'], unique=False)
    op.drop_index(op.f('idx_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_index(op.f('idx_users_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_table('nonces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonces',
    sa.Column('wallet_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nonce', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('wallet_address', name=op.f('nonces_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_premium', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('wallet_address', name=op.f('users_wallet_address_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tree', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('idx_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.drop_index('idx_vaults_owner_wallet', table_name='vaults')
    op.drop_index('idx_vaults_doc_hash', table_name='vaults')
    op.drop_index('idx_vaults_created_at', table_name='vaults')
    op.drop_table('vaults')
    # ### end Alembic commands ###
